# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

nodejs_version: 0.10

install:
  - cd wp8
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - msbuild /version
  - wp8\bin\create .\testcreate
  - .\testcreate\cordova\build